### ISSUE TITLE
How to generate the PDF

### ISSUE THREAD

**Issue by emanuelef** [our-bts/raml2pdf#1]
Hi,
Great idea for a tool to generate PDF from RAML, the only project I've found so far.
I'm trying to use this to convert a RAML file I generated. I used the raml2html and it works.
I wanted to generate a PDF but I don't know how to do that. I followed the steps and installed everything. Thanks for any help.

**Comment by xiajinchun** [comment]
Hi,
The meaning you said is that having wrong in generating PDF from generated HTML template?
If it is like this, maybe unsuccessful installation for [Wkhtmltopdf](http://wkhtmltopdf.org/downloads.html) (various OS with various version), or unavailable path value for `wkhtmltopdfCommand` in `congfig.js`.
And then you sent a HTTP request with POST method using REST test tool(e.g. Postman app in Chrome).
Thanks.

**Comment by Aashmeet** [comment]
I cannot get the pdf generated and getting no response from postman
