### ISSUE TITLE
Documentation on how to generate a PDF ?

### ISSUE THREAD

**Issue by laurentperez** [our-bts/raml2pdf#2]
Hi

I don't figure out how to actually use raml2pdf. wkhtmltopdf is installed, I did a git clone of your repository, npm installed, but I do not understand where to go. Under node, var pdf = require("raml2pdf"); can't find the module.

I see no runnable server for host:8000/raml2pdf within the code. Can you point me to what's missing ?

Thanks
laurent

**Comment by xiajinchun** [comment]
Hi,
After wkhtmltopdf installed, you should change directory to raml2pdf, run `node index`, the server will running, and then use REST Client Test Tools(e.g. Postman in chrome) to send "http://127.0.01:8000/raml2pdf" POST request with right Request Data.

Hope helpful.

**Comment by laurentperez** [comment]
Hi
Sorry but it's not working
Under Postman, POSTing in "raw" body https://raw.githubusercontent.com/our-bts/raml2pdf/master/examples/example.json results in ``{"error":"No RAML Specification defined"}`

**Comment by xiajinchun** [comment]
Hi,
Are you sure you add 'Content-Type: application/json' in POST request headers?
Helpful.

**Comment by laurentperez** [comment]
yes it works with the header, thanks
should document this :)

**Comment by nsejim** [comment]
Hi, 

I think I am missing a step.
Where do I found the generated pdf? 
After posting, I get the below pdf source as response 
(I have truncated it for readability).

Thanks for your help ....

%PDF-1.4
1 0 obj
<<
/Title (��Example API documentation)
/Creator (��wkhtmltopdf 0.12.2.1)
/Producer (��Qt 4.8.6)
/CreationDate (D:20151207185142+01'00')

> > endobj
> > 3 0 obj
